In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
pip install tensorflow


  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached markdown-3.10.1-py3-none-any.whl.metadata (5.1 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
   ---------------------------------------- 0.0/331.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/331.7 MB ? eta -:--:--
   -----------------------

   ------------ --------------------------- 100.2/331.7 MB 3.2 MB/s eta 0:01:12
   ------------ --------------------------- 100.4/331.7 MB 2.9 MB/s eta 0:01:20
   ------------ --------------------------- 101.2/331.7 MB 3.1 MB/s eta 0:01:15
   ------------ --------------------------- 101.8/331.7 MB 3.0 MB/s eta 0:01:18
   ------------ --------------------------- 102.0/331.7 MB 3.0 MB/s eta 0:01:18
   ------------ --------------------------- 102.8/331.7 MB 2.9 MB/s eta 0:01:20
   ------------ --------------------------- 103.3/331.7 MB 2.9 MB/s eta 0:01:21
   ------------ --------------------------- 103.6/331.7 MB 2.9 MB/s eta 0:01:20
   ------------ --------------------------- 103.9/331.7 MB 2.7 MB/s eta 0:01:24
   ------------ --------------------------- 105.2/331.7 MB 2.8 MB/s eta 0:01:20
   ------------ --------------------------- 106.7/331.7 MB 3.1 MB/s eta 0:01:14
   ------------- -------------------------- 108.3/331.7 MB 3.2 MB/s eta 0:01:09
   ------------- -----------------------

In [8]:
tf.__version__

'2.20.0'

In [ ]:
dataset =pd.read_csv(r"C:\Users\ANITHA\Downloads\10th- Ensamble learning (1)\10th- Ensamble learning\7.XGBOOST\Churn_Modelling.csv")

In [12]:
dataset

apst  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0         1    15634602   Hargrave          619      delhi  Female   42   
1         2    15647311       Hill          608  bangalore  Female   41   
2         3    15619304       Onio          502      delhi  Female   42   
3         4    15701354       Boni          699      delhi  Female   39   
4         5    15737888   Mitchell          850  bangalore  Female   43   
...     ...         ...        ...          ...        ...     ...  ...   
9995   9996    15606229   Obijiaku          771      delhi    Male   39   
9996   9997    15569892  Johnstone          516      delhi    Male   35   
9997   9998    15584532        Liu          709      delhi  Female   36   
9998   9999    15682355  Sabbatini          772     mumbai    Male   42   
9999  10000    15628319     Walker          792      delhi  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [34]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)


[[619 'delhi' 'Female' ... 1 1 101348.88]
 [608 'bangalore' 'Female' ... 0 1 112542.58]
 [502 'delhi' 'Female' ... 1 0 113931.57]
 ...
 [709 'delhi' 'Female' ... 0 1 42085.58]
 [772 'mumbai' 'Male' ... 1 0 92888.52]
 [792 'delhi' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [35]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'delhi' 0 ... 1 1 101348.88]
 [608 'bangalore' 0 ... 0 1 112542.58]
 [502 'delhi' 0 ... 1 0 113931.57]
 ...
 [709 'delhi' 0 ... 0 1 42085.58]
 [772 'mumbai' 1 ... 1 0 92888.52]
 [792 'delhi' 0 ... 1 0 38190.78]]


In [38]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [0.0 1.0 0.0 ... 1 0 113931.57]
 ...
 [0.0 1.0 0.0 ... 0 1 42085.58]
 [0.0 0.0 1.0 ... 1 0 92888.52]
 [0.0 1.0 0.0 ... 1 0 38190.78]]


In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[-0.57380915  0.99720391 -0.57873591 ...  0.64609167  0.97024255
   0.02188649]
 [ 1.74273971 -1.00280393 -0.57873591 ... -1.54776799  0.97024255
   0.21653375]
 [-0.57380915  0.99720391 -0.57873591 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-0.57380915  0.99720391 -0.57873591 ... -1.54776799  0.97024255
  -1.00864308]
 [-0.57380915 -1.00280393  1.72790383 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.57380915  0.99720391 -0.57873591 ...  0.64609167 -1.03067011
  -1.07636976]]


In [40]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [41]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [42]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [43]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [44]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))


In [45]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))


In [46]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


In [47]:

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [49]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 6)


Epoch 1/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.4288
Epoch 2/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4272
Epoch 3/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.4252
Epoch 4/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4235
Epoch 5/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4207
Epoch 6/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7960 - loss: 0.4170


In [50]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [51]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1594    1]
 [ 405    0]]


In [52]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)




0.797
