# Numpy crash course

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
my_list =[0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [19]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [21]:
type(arr)

numpy.ndarray

In [33]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [35]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(20,10)  # The first element should be less than second element 

array([], dtype=int32)

In [41]:
np.arange(-20,30)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29])

In [43]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [47]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [49]:
np.arange()

TypeError: arange() requires stop to be specified.

In [51]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [53]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [55]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [61]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [63]:
zero=np.zeros([2,2,])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [65]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [69]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [79]:
np.ones(3)

array([1., 1., 1.])

In [81]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [87]:
np.three((3,4))

AttributeError: module 'numpy' has no attribute 'three'

In [89]:
rand(3,2)

NameError: name 'rand' is not defined

In [91]:
random.rand(3,2)

NameError: name 'random' is not defined

In [100]:
np.random.rand(5)

array([0.13170956, 0.89909738, 0.62352278, 0.19180381, 0.68988869])

In [116]:
np.random.rand(3,5)

array([[0.06278264, 0.2441652 , 0.54708412, 0.16843953, 0.61993642],
       [0.70013403, 0.48035317, 0.19808875, 0.81665714, 0.38786499],
       [0.39669408, 0.07232765, 0.72101399, 0.30466118, 0.48278368]])

In [3]:
np.random.randint(4,6)

NameError: name 'np' is not defined

In [5]:
np.random.randint(0,9,4)

NameError: name 'np' is not defined

In [130]:
np.random.randint(30,20,10)

ValueError: low >= high

In [134]:
np.random.randint(-30,20,10)

array([ 10, -27, -21,  13, -15,   9,   7,  -8,  12,  -5])

In [139]:
np.random.randint(20,30,10,40)

TypeError: Cannot interpret '40' as a data type

In [148]:
np.random.randint(10,40,(10,10))

array([[33, 17, 25, 11, 17, 13, 23, 36, 17, 27],
       [36, 34, 39, 14, 18, 17, 27, 35, 25, 36],
       [12, 38, 22, 23, 33, 33, 11, 29, 14, 33],
       [21, 22, 32, 32, 31, 20, 31, 35, 18, 30],
       [31, 19, 30, 36, 37, 14, 14, 24, 31, 34],
       [23, 30, 10, 15, 17, 33, 20, 37, 30, 27],
       [13, 28, 24, 30, 24, 28, 17, 17, 24, 39],
       [28, 28, 39, 22, 27, 22, 16, 31, 14, 36],
       [26, 39, 25, 22, 11, 13, 22, 10, 39, 18],
       [23, 20, 26, 16, 27, 15, 33, 17, 22, 15]])

In [150]:
np.random.randint(1,100,(12,12))

array([[37, 24, 97, 18, 70, 76, 83, 87, 89, 91, 11, 81],
       [55, 32, 82, 28, 29, 56, 27,  8,  9, 54, 74, 38],
       [35, 87, 38, 19, 44, 13, 18,  2, 39, 57, 29, 97],
       [91, 50, 31, 93, 59, 77, 78,  8, 69, 18, 14, 47],
       [41, 33, 28, 89, 51, 45, 27, 53, 39, 87, 35, 72],
       [47, 24, 90, 89, 63,  3,  4, 34, 43,  7, 57, 59],
       [27,  5, 51, 87, 23, 43, 75, 27, 46,  4, 42, 34],
       [14, 28, 28, 73, 30, 56, 15, 22, 47,  8, 41, 53],
       [70, 38, 74,  3, 74, 39, 86, 64, 55, 22, 33, 97],
       [66, 90, 95, 98, 19, 11, 21, 63, 26, 80, 47, 93],
       [39, 37, 16, 82, 21, 42, 22, 33, 35, 32, 85, 12],
       [88, 22, 11, 44, 48, 62, 66,  5, 10, 99, 55, 78]])

In [156]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [158]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [160]:
np.arange(1,13).reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [166]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [168]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# slicing in matrix

In [175]:
b=np.random.randint(10,20,(5,4))
b

array([[16, 17, 16, 12],
       [13, 11, 15, 14],
       [15, 14, 14, 11],
       [10, 13, 13, 19],
       [16, 12, 10, 10]])

In [177]:
b[:]

array([[16, 17, 16, 12],
       [13, 11, 15, 14],
       [15, 14, 14, 11],
       [10, 13, 13, 19],
       [16, 12, 10, 10]])

In [179]:
b[0]

array([16, 17, 16, 12])

In [181]:
b[4]

array([16, 12, 10, 10])

In [183]:
b[3]

array([10, 13, 13, 19])

In [185]:
b[-4]

array([13, 11, 15, 14])

In [187]:
arr

array([0, 1, 2, 3, 4, 5])

In [189]:
b[:-3]

array([[16, 17, 16, 12],
       [13, 11, 15, 14]])

In [191]:
b[:]

array([[16, 17, 16, 12],
       [13, 11, 15, 14],
       [15, 14, 14, 11],
       [10, 13, 13, 19],
       [16, 12, 10, 10]])

In [193]:
b[:-1]

array([[16, 17, 16, 12],
       [13, 11, 15, 14],
       [15, 14, 14, 11],
       [10, 13, 13, 19]])

In [195]:
arr

array([0, 1, 2, 3, 4, 5])

In [197]:
arr.max()

5

In [199]:
arr.min()

0

In [201]:
arr.mean()

2.5

In [203]:
arr

array([0, 1, 2, 3, 4, 5])

In [205]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [211]:
from numpy import *
a = array ([10,30,50,5,80,])
median(a)



30.0

# Without work on import* can you plz find the median,mode)

In [214]:
arr

array([0, 1, 2, 3, 4, 5])

In [220]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [222]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [224]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [246]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [232]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [254]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
row=4
col=5

In [258]:
col

5

In [260]:
row

4

In [262]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
mat[row,col]

45

In [266]:
mat[4,5]

45

In [268]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

#with slicing

In [278]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [280]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [282]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [284]:
mat[col:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [286]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [288]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [290]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [293]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [295]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [297]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [301]:
mat[2:6,2:4] #1:5-->only row part ///1:3--it indicates only column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [303]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [305]:
mat[2:3,2:3]

array([[22]])

In [307]:
mat[3:4,2:3]

array([[32]])

In [309]:
mat[2:3,4:5]

array([[24]])

# Operations

In [150]:
a=np.random.randint(10,20,10)
a

array([19, 13, 15, 12, 14, 17, 16, 18, 18, 11])

In [152]:
id(a)

2072221041840

In [158]:
arr2=np.random.randint(0,100,(10,10))
print(arr2)

[[42 77 21 73  0 10 43 58 23 59]
 [ 2 98 62 35 94 67 82 46 99 20]
 [81 50 27 14 41 58 65 36 10 86]
 [43 11  2 51 80 32 54  0 38 19]
 [46 42 56 60 77 30 24  2  3 94]
 [98 13 40 72 19 95 72 26 66 52]
 [67 61 14 96  4 67 11 86 77 75]
 [56 16 24 29 21 25 80 60 61 83]
 [33 32 70 85 31 13 71 56 24 79]
 [41 18 40 54 79 11 38 93  1 95]]


In [162]:
arr2[:]

array([[42, 77, 21, 73,  0, 10, 43, 58, 23, 59],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [46, 42, 56, 60, 77, 30, 24,  2,  3, 94],
       [98, 13, 40, 72, 19, 95, 72, 26, 66, 52],
       [67, 61, 14, 96,  4, 67, 11, 86, 77, 75],
       [56, 16, 24, 29, 21, 25, 80, 60, 61, 83],
       [33, 32, 70, 85, 31, 13, 71, 56, 24, 79],
       [41, 18, 40, 54, 79, 11, 38, 93,  1, 95]])

In [164]:
arr2[:4]

array([[42, 77, 21, 73,  0, 10, 43, 58, 23, 59],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19]])

In [166]:
arr2[0:5]

array([[42, 77, 21, 73,  0, 10, 43, 58, 23, 59],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [46, 42, 56, 60, 77, 30, 24,  2,  3, 94]])

In [168]:
arr2[1,4]

94

In [170]:
arr2[-5,5]

95

In [172]:
arr2

array([[42, 77, 21, 73,  0, 10, 43, 58, 23, 59],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [46, 42, 56, 60, 77, 30, 24,  2,  3, 94],
       [98, 13, 40, 72, 19, 95, 72, 26, 66, 52],
       [67, 61, 14, 96,  4, 67, 11, 86, 77, 75],
       [56, 16, 24, 29, 21, 25, 80, 60, 61, 83],
       [33, 32, 70, 85, 31, 13, 71, 56, 24, 79],
       [41, 18, 40, 54, 79, 11, 38, 93,  1, 95]])

In [174]:
arr2[-5,-5]

95

In [176]:
arr2[-1,-2]

1

In [178]:
arr2[::-1]

array([[41, 18, 40, 54, 79, 11, 38, 93,  1, 95],
       [33, 32, 70, 85, 31, 13, 71, 56, 24, 79],
       [56, 16, 24, 29, 21, 25, 80, 60, 61, 83],
       [67, 61, 14, 96,  4, 67, 11, 86, 77, 75],
       [98, 13, 40, 72, 19, 95, 72, 26, 66, 52],
       [46, 42, 56, 60, 77, 30, 24,  2,  3, 94],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [42, 77, 21, 73,  0, 10, 43, 58, 23, 59]])

In [180]:
arr2[::-2]

array([[41, 18, 40, 54, 79, 11, 38, 93,  1, 95],
       [56, 16, 24, 29, 21, 25, 80, 60, 61, 83],
       [98, 13, 40, 72, 19, 95, 72, 26, 66, 52],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20]])

# Masking

In [187]:
mat=np.arange(0,100).reshape(10,10) #we also called as filter
arr2

array([[42, 77, 21, 73,  0, 10, 43, 58, 23, 59],
       [ 2, 98, 62, 35, 94, 67, 82, 46, 99, 20],
       [81, 50, 27, 14, 41, 58, 65, 36, 10, 86],
       [43, 11,  2, 51, 80, 32, 54,  0, 38, 19],
       [46, 42, 56, 60, 77, 30, 24,  2,  3, 94],
       [98, 13, 40, 72, 19, 95, 72, 26, 66, 52],
       [67, 61, 14, 96,  4, 67, 11, 86, 77, 75],
       [56, 16, 24, 29, 21, 25, 80, 60, 61, 83],
       [33, 32, 70, 85, 31, 13, 71, 56, 24, 79],
       [41, 18, 40, 54, 79, 11, 38, 93,  1, 95]])

In [189]:
mat  #we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
id(mat)

2072221379408

In [193]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [195]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [197]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [201]:
mat[mat==50]

array([50])

In [203]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [207]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [209]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

a3=mat[mat<=50]
a3

# Python Program to generate otp

In [232]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits='012345'
    otp=''.join (random.choice(digits)for _ in range(length))
    return otp

#Example usage
otp_length =4
otp=generate_otp(otp_length)
print(f" Your OTP is:{otp}")
    

 Your OTP is:2504


In [234]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [236]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [238]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001E27A035E80>


In [240]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]


# ARRAY CREATION 

In [46]:
import numpy as np
np.array([2,4,65,322,78,2])

array([  2,   4,  65, 322,  78,   2])

In [48]:
a=np.array([2,4,65,322,78,2]) #vector
print(a)

[  2   4  65 322  78   2]


In [50]:
type(a)

numpy.ndarray

In [ ]:
#creating an array 

In [5]:
import numpy as np
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [ ]:
#create an array

In [9]:
b=np.arange(0,10,2)
print('Array b:',b)

Array b: [0 2 4 6 8]


In [ ]:
#create an aaray filled with zeros

In [11]:
d=np.zeros((2,3))
print('Arrayd:\n',d)

Arrayd:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating an array fulled with ones

In [13]:
e=np.ones((3,2))
print('Array e:\n',e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# create an identity

In [15]:
f=np.eye(4)
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Operations

In [ ]:
#

# Array Manipulation function

In [19]:
a1=np.array([1,2,3])
reshape=np.reshape(a1,(1,3))
print("reshape array:",reshape)

reshape array: [[1 2 3]]


#reshape an array

In [11]:
import numpy as np
a1=np.array([1,2,3])
reshaped =np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [26]:
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
flattened=np.ravel(f1)
print("flattened array:",flattened)

flattened array: [1 2 3 4 5 6 7 8]


In [56]:
e1=np.array([[1,2],[3,4]])
transpose=np.transpose(e1)
print("transpose array:\n",transpose)

transpose array:
 [[1 3]
 [2 4]]


In [ ]:
#

In [44]:
a2=np.array([1,2])
b2=np.array([3,4])
stack = np.vstack([a2,b2])
print(stack)

[[1 2]
 [3 4]]


#dtype

In [59]:
np.array([11,23,44],dtype=float)


array([11., 23., 44.])

In [61]:
np.array([10,15,20],dtype=int)

array([10, 15, 20])

In [65]:
np.array([10,15,0],dtype=bool)

array([ True,  True, False])

In [67]:
np.array([20,3,40],dtype=complex)

array([20.+0.j,  3.+0.j, 40.+0.j])

# Mathematical Functions

In [18]:
#add two arrays
g=np.array([1,2,3,4])
added=np.add(g,3) 
print("Added 2 to g:",added)

Added 2 to g: [4 5 6 7]


In [20]:
#square each element
squared= np.power(g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [22]:
#square root of each element
sqrt_val=np.sqrt(g)
print("square root of g:",sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [24]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [26]:
#Dot product of two arrays
a2 = np.array([1,2,3])
dot_product=np.dot(a2,g)
print("Dot product of a and g:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [30]:
a3 = np.array([1,2,3])
dot_product=np.dot(a1,a2)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# Statistical Functions

In [35]:
s= np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [37]:
#standard deviation of an array
std_dev=np.std(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [39]:
#Minimum element of an array
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [41]:
#Maximum element of an array
maximum = np.max(s)
print("max of s:",maximum)

max of s: 4


# Linear Algebra Function

In [46]:
#create a matrix
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


# Random Sampling Functions

In [57]:
#Generate random values between 0 and 1
random_vals=np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.13774647 0.6977434  0.56209988]


In [62]:
#generate random intergers 
rand_ints=np.random.randint(0,10,size=5) 
print("Random intergers:",rand_ints)

Random intergers: [5 7 0 9 3]


In [66]:
#set seed for reproducibility
np.random.seed(0)

In [73]:
#generate random intergers
rand_ints = np.random.randint(0,10,size=5)
print("Random intergers:",rand_ints)

Random intergers: [9 3 5 2 4]


In [87]:
# set seed for reproducibility
np.random.seed(0)
#generate random integers
rand_int = np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [9 3 5 2 4]


# Boolean & Logical Functions

In [94]:
#check if all elements are true
#all
logical_test= np.array([True,False,False])
all_true=np.all(logical_test)  #check if all True
print("All elements True:",all_true)


All elements True: False


In [104]:
#check if all elements are True
logical_test= np.array([True,True,False])
all_true=np.all(logical_test)  #check if all True
print("All elements True:",all_true)

All elements True: False


# Set Operations

In [109]:
#Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection =np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [113]:
#union of two arrays
union= np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


In [115]:
# Array Attribute Functions

In [117]:
#Array attributes
a = np.array([1,2,3])
shape=a.shape  #shape of the array
size= a.size   #number of elements
dimension=a.ndim #number of dimensions
dtype=a.dtype  #data type of the array

print("shape of a:",shape)
print("size of a:",size)
print("Number of dimension of a:",dimension)
print("Data type of a:",dtype)

shape of a: (3,)
size of a: 3
Number of dimension of a: 1
Data type of a: int32


# Other Functions

In [120]:
#create a copy of an array
a=np.array([1,2,3])
copied_array=np.copy(a)
print("Copied array:",copied_array)

Copied array: [1 2 3]


In [130]:
#size in bytes of an array
array_size_in_bytes=a.nbytes
print("size of a in bytes:",array_size_in_bytes)

size of a in bytes: 12


In [141]:
#check if two arrays share memory
hared=np.shares_memory(a,copied_array)
print("Do a and copied_array share memory?",shared)


NameError: name 'shared' is not defined